name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello everyone from pipeline!"

  test-utils:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Test utils
        run: npm test utils.test.js

  test-app:
    runs-on: ubuntu-latest
    needs: test-utils
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v3

      - name: Setup PSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: nc_news_test
          postgresql user: oksanagerasymenko
          postgresql password: postgres
      - name: Install dependencies
        run: npm install
      - name: Test app
        run: PGDATABASE = nc_news_test PGUSER=oksanagerasymenko PGPASSWORD=postgres npm test app.test.js
